### ISSUE TITLE
Replace 'executable thing' with just 'executable'

### ISSUE THREAD

**Issue by Zarquan** [ivoa-std/ExecutionBroker#57]
Not sure about this yet, but it replacing '_executable_ thing' with just  '_executable_' might make section 1.2 easier to read.

**Comment by bertocco** [comment]
Why we do not use task or job?

**Comment by Zarquan** [comment]
Both 'task' and 'job' have other established meanings in people's heads. I am trying to explain the very abstract concept of an 'executable thing' that covers a wide range of different executables.

The 'executable' is only part of the task/job that we end up with. The request and offers also contain details of the compute and storage resources.  

In fact in #52 I'm thinking of replacing the word 'job' with 'session' because we want to do slightly different things with a session than we can with a job.

All of this is based on talking to people about the EB and seeing if their reaction to words that they think they know matches what we are trying to explain here. I'm learning to avoid 'task' and 'job' because people have their own (different) ideas of what they think those words mean. 

This issue is here because _'executable thing'_ works well at emphasising the abstract concept, it just makes the text hard to read. I was wondering if we could shorten it to _'executable'_ and still achieve the same abstract concept.

**Comment by Zarquan** [comment]
I think it was the italics on one word but not both that made it look crap.
Changed "_executable_ thing" to "_executable thing_" to see if this looks better.

**Comment by Zarquan** [comment]
Also found a nice hack to handle plurals inside the italics.

**Comment by Zarquan** [comment]
Closing this for now, see if the changes in #60 look OK.
